import AppLayout from '@/layouts/app-layout';
import { type BreadcrumbItem } from '@/types';
import { Head, Link, usePage } from '@inertiajs/react';

type Report = {
    id: number;
    title: string;
    type: 'progress' | 'financial' | 'task' | 'custom';
    content: string;
    report_date: string;
    created_at: string;
    project?: {
        id: number;
        name: string;
    };
    user?: {
        id: number;
        name: string;
    };
};

const breadcrumbs: BreadcrumbItem[] = [
    { title: 'Dashboard', href: '/dashboard' },
    { title: 'Reports', href: '/reports' },
];

export default function ReportShow() {
    const { report } = usePage().props as unknown as { report: Report };

    return (
        <AppLayout breadcrumbs={[...breadcrumbs, { title: report.title, href: `/reports/${report.id}` }]}>
            <Head title={report.title} />

            <div className="space-y-6 p-6">
                <div className="flex items-center justify-between">
                    <h1 className="text-2xl font-bold">{report.title}</h1>
                    <Link href={`/reports/${report.id}/edit`} className="rounded bg-yellow-500 px-4 py-2 text-white hover:bg-yellow-600">
                        Edit
                    </Link>
                </div>

                <div className="space-y-2">
                    <p>
                        <span className="font-semibold">Type:</span> {report.type}
                    </p>
                    <p>
                        <span className="font-semibold">Date:</span> {report.report_date}
                    </p>
                    <p>
                        <span className="font-semibold">Generated By:</span> {report.user?.name ?? 'Unknown'}
                    </p>
                    <p>
                        <span className="font-semibold">Project:</span> {report.project?.name ?? 'None'}
                    </p>
                </div>

                <div>
                    <h2 className="text-lg font-semibold">Content</h2>
                    <div className="prose max-w-full">
                        <p>{report.content}</p>
                    </div>
                </div>
            </div>
        </AppLayout>
    );
}
